@baseUrl = http://localhost:3000

POST {{baseUrl}}/user
Content-Type: application/json

{
  "externalId": null,
  "firstName": "Henrique",
  "lastName": "Sampaio",
  "role": "ALUNO",
  "syncMode": "NONE"
}

###
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "userId": "7565ad43-17ce-41ac-aaf8-511bddf4bf29"
}

###
POST {{baseUrl}}/institution
Content-Type: application/json

{
  "name": "maplebear",
  "apiKey": "f7a8442f-4ac5-4659-894f-d8663800b521"
}

###
POST {{baseUrl}}/unit
Content-Type: application/json

{
  "institutionId": "f2d31935-3753-4e9e-9409-2285de0a2ea3",
  "alias": "Maplebear Capão Redondo",
  "address": null,
  "externalId": "1e91311d-f082-42ce-9a9d-c7a8cfbb2710"
}

###
POST {{baseUrl}}/unit/82dbae8c-1663-4c6b-b127-dddf12960c4f/classroom
Content-Type: application/json

{
  "externalId": null,
  "title": "5 ano B",
  "location": null
}