@baseUrl = http://localhost:3000

POST {{baseUrl}}/user
Content-Type: application/json

{
  "externalId": null,
  "firstName": "Kento",
  "lastName": "Nanami",
  "role": "PROFESSOR",
  "syncMode": "NONE"
}

###
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "userId": "aa444639-8ad5-4af1-ba7e-63937663e402"
}

###
DELETE {{baseUrl}}/accounts/e4393ebc-09aa-4c3b-a76b-d14f822ac86d

###
POST {{baseUrl}}/accounts/import/google
Content-Type: application/json

{
  "orgPath": "/Integrador-teste/Maplebear - Krypton"
}

###
POST {{baseUrl}}/institution
Content-Type: application/json

{
  "name": "maplebear",
  "apiKey": "f7a8442f-4ac5-4659-894f-d8663800b521"
}

###
POST {{baseUrl}}/unit
Content-Type: application/json

{
  "institutionId": "a8fceb2f-abfc-473a-b78f-46b263d86217",
  "alias": "Maplebear Krypton",
  "address": null,
  "externalId": "1e91311d-f082-42ce-9a9d-c7a8cfbb2710"
}

###
POST {{baseUrl}}/unit/3b2f429c-5ebb-4d7d-9c6d-6f1657591b1b/classroom
Content-Type: application/json

{
  "title": "JUJUTSU Tokio Grau especial",
  "ownerAccountId": "39ea5b1b-6229-4c77-bc82-762f1b0fec3e"
}

###
POST {{baseUrl}}/classroom/1e1ea83b-6119-4462-b181-8c3c643865ff/add
Content-Type: application/json

{
  "userId": "7e15e6dd-f3a8-45b1-a52e-925da0d10d4c"  
}