@baseUrl = http://localhost:3000

POST {{baseUrl}}/user
Content-Type: application/json

{
  "externalId": null,
  "firstName": "Yuta",
  "lastName": "Okkotsu",
  "role": "ALUNO",
  "syncMode": "AUTO"
}

###
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "userId": "7134eb49-fe1b-4fee-8135-79d49a112eb9"
}

###
POST {{baseUrl}}/institution
Content-Type: application/json

{
  "name": "maplebear",
  "apiKey": "f7a8442f-4ac5-4659-894f-d8663800b521"
}

###
POST {{baseUrl}}/unit
Content-Type: application/json

{
  "institutionId": "2416fa92-5c7a-44b9-af69-d9bc2696e59f",
  "alias": "Maplebear Capão Redondo",
  "address": null,
  "externalId": "1e91311d-f082-42ce-9a9d-c7a8cfbb2710"
}

###
POST {{baseUrl}}/unit/bd7ed514-58a3-4f5c-84c1-c832ad1c05c5/classroom
Content-Type: application/json

{
  "title": "7 ano B inglês",
  "ownerAccountId": "4cbc6add-b0d5-4b92-9308-45cc8730037e"
}

###
POST {{baseUrl}}/classroom/1e1ea83b-6119-4462-b181-8c3c643865ff/add
Content-Type: application/json

{
  "userId": "7e15e6dd-f3a8-45b1-a52e-925da0d10d4c"  
}